CREATE TABLE {db}.{schema}.dim_Employees_SCD2(
EmployeeID_SK int IDENTITY(1,1) NOT NULL,
BusinessKey int NOT NULL,
LastName VARCHAR(50),
FirstName VARCHAR(50),
Title VARCHAR(50),
TitleOfCourtesy VARCHAR(50),
BirthDate datetime,
HireDate datetime,
Address VARCHAR(50),
City VARCHAR(50),
Region VARCHAR(50),
PostalCode VARCHAR(50),
Country VARCHAR(50),
HomePhone VARCHAR(50),
Extension VARCHAR(50),
Notes VARCHAR(500),
PhotoPath VARCHAR(50),
ValidFrom INT NULL,
ValidTo INT NULL,
IsCurrent BIT NULL
) ON [PRIMARY];
